---

version: '3.8'
services:
  locust:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py -L DEBUG -H http://app:8090
  # master:
  #   image: locustio/locust
  #   ports:
  #    - "8089:8089"
  #   volumes:
  #     - ./:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  # worker:
  #   image: locustio/locust
  #   volumes:
  #     - ./:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --worker --master-host master
